"""approval-notifier — never miss or misread an approval prompt again.

v1.2.2: late AI explanations are delivered (marked 补发) instead of
silently dropped; optional auxiliary.approval model for fast breakdowns.
v1.2.0: the fixed 5-field Chinese breakdown now prints INTO the terminal
while the y/n prompt is waiting (toasts become secondary delivery).
v1.1.0: custom alert sound (looping WAV, e.g. F1 radio chime) with
automatic fallback to the built-in beep+alarm.
v1.0.0: two-stage alerts with plain-language Chinese command explanations.

Scenario: the user backgrounds the terminal running Hermes. When a
dangerous-command approval prompt appears, they (a) may not see it
(60s default auto-deny) and (b) can't read raw shell syntax anyway.

Behavior now, in two stages:
- Stage 1 (immediate): Windows Toast with the risk category translated
  to Chinese via a static table (deterministic, zero latency, no LLM),
  plus the raw command. Alarm tone + console beeps start immediately
  and repeat every 15s until the approval is resolved.
- Stage 2 (a few seconds later, async): a second Toast titled
  「命令解读」 generated by the user's ACTIVE main model (via
  agent.auxiliary_client.call_llm with config.yaml's model section,
  read fresh per call so model switches are honored): one line saying
  what the command concretely does, one line with a risk verdict. If
  the LLM fails/times out, stage 2 is silently skipped — stage 1
  already fired.

The approval decision itself still happens in the terminal (y/n); the
toasts are observers only. Never blocks the agent thread.
"""

import base64
import logging
import os
import subprocess
import sys
import threading
import time
from xml.sax.saxutils import escape

logger = logging.getLogger(__name__)

_BELL_INTERVAL_S = 15.0        # repeating beep interval
_BELL_MAX_S = 900.0            # hard stop: 15 minutes of beeping max
_LLM_TIMEOUT_S = 25.0          # stage-2 explanation budget
_LLM_MAX_INPUT_CHARS = 2000    # truncate huge commands before the LLM
_AUMID = ("{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}"
          r"\WindowsPowerShell\v1.0\powershell.exe")

_stop = threading.Event()
_gen = 0                       # request generation counter
_gen_lock = threading.Lock()
_ctx = None                    # plugin ctx (saved at register()) for ctx.llm

# ------------------------------------------------------------------
# Static EN->CN translation for Hermes' known approval rule names
# (from tools/approval.py DANGEROUS_PATTERNS / HARDLINE_PATTERNS).
# Unknown strings pass through untranslated.
# ------------------------------------------------------------------
_DESC_CN = {
    "recursive delete of root filesystem": "删除整个系统盘的文件(极度危险,系统会直接拦截)",
    "recursive delete of system directory": "删除系统关键目录,电脑可能无法开机",
    "recursive delete of home directory": "删除你的用户主目录(桌面、文档都在里面)",
    "format filesystem (mkfs)": "格式化磁盘分区,盘上数据全部清空",
    "dd to raw block device": "直接向物理硬盘写入,等同整盘覆盖数据",
    "redirect to raw block device": "把内容写进物理硬盘,等同整盘覆盖数据",
    "fork bomb": "恶意死循环,瞬间耗尽电脑性能导致死机",
    "kill all processes": "关掉电脑上所有程序",
    "force kill processes": "强制关掉一批程序",
    "system shutdown/reboot": "马上要关机或重启电脑",
    "init 0/6 (shutdown/reboot)": "关机或重启(底层方式)",
    "systemctl poweroff/reboot": "关机或重启(服务方式)",
    "telinit 0/6 (shutdown/reboot)": "关机或重启",
    "stop/restart system service": "停止或重启某个系统服务",
    "sudo password guessing via stdin (sudo -S)": "尝试自动输入管理员密码(提权操作)",
    "delete in root path": "在系统根目录下删除文件",
    "recursive delete": "连同子文件夹里的所有文件一起删除",
    "recursive delete (long flag)": "连同子文件夹里的所有文件一起删除",
    "world/other-writable permissions": "把文件改为任何用户都能改写(安全隐患)",
    "recursive world/other-writable (long flag)": "批量把文件改为任何用户都能改写",
    "recursive chown to root": "批量把文件归属权改为系统管理员",
    "recursive chown to root (long flag)": "批量把文件归属权改为系统管理员",
    "format filesystem": "格式化磁盘分区,数据清空",
    "disk copy": "磁盘级复制,可能整盘覆盖数据",
    "write to block device": "直接写入硬盘设备,可能覆盖数据",
    "SQL DROP": "数据库:删表或删库,数据不可恢复",
    "SQL DELETE without WHERE": "数据库:没有筛选条件,会删光整张表",
    "SQL TRUNCATE": "数据库:清空整张表",
    "overwrite system config": "覆盖系统配置文件,可能影响电脑行为",
    "overwrite system file via tee": "写入并覆盖某个系统文件",
    "overwrite system file via redirection": "输出重定向,可能覆盖某个系统文件",
    "overwrite project env/config via tee": "改写项目的配置或密钥文件(.env等)",
    "overwrite project env/config via redirection": "改写项目的配置或密钥文件(.env等)",
    "overwrite project env/config file": "改写项目的配置或密钥文件(.env等)",
    "copy/move file into /etc/": "往系统配置目录里放文件",
    "in-place edit of system config": "就地修改系统配置文件",
    "in-place edit of system config (long flag)": "就地修改系统配置文件",
    "shell command via -c/-lc flag": "命令行里内嵌了一段 shell 命令执行",
    "script execution via -e/-c flag": "程序内嵌一小段代码直接运行,多为正常操作(常见误报)",
    "script execution via heredoc": "内嵌一段脚本直接运行",
    "pipe remote content to shell": "把网上下载的内容直接当命令运行,极危险",
    "execute remote script via process substitution": "直接运行网络上的脚本,极危险",
    "chmod +x followed by immediate execution": "给文件加执行权限后马上运行(可疑脚本套路)",
    "xargs with rm": "按搜索结果批量删除文件",
    "find -exec rm": "按搜索结果批量删除文件",
    "find -delete": "按搜索结果批量删除文件",
    "stop/restart hermes gateway (kills running agents)": "重启 Hermes 网关,正在跑的任务会中断",
    "hermes update (restarts gateway, kills running agents)": "更新 Hermes 本体,正在跑的任务会中断",
    "start gateway outside systemd (use 'systemctl --user restart hermes-gateway')": "以非标准方式启动网关",
    "kill hermes/gateway process (self-termination)": "结束 Hermes 自己的进程(自杀式)",
    "kill process via pgrep expansion (self-termination)": "按名字批量杀进程,可能误伤 Hermes 自己",
    "kill process via backtick pgrep expansion (self-termination)": "按名字批量杀进程,可能误伤 Hermes 自己",
    "git reset --hard (destroys uncommitted changes)": "代码仓库回退到上次提交,未保存的修改全丢",
    "git force push (rewrites remote history)": "代码强推到服务器,覆盖远端历史记录",
    "git force push short flag (rewrites remote history)": "代码强推到服务器,覆盖远端历史记录",
    "git clean with force (deletes untracked files)": "清理代码仓库,所有未登记的文件被删",
    "git branch force delete": "强制删除代码分支,未合并的内容会丢",
    # --- Windows / PowerShell / container rules (v1.2.1 full coverage) ---
    "PowerShell destructive delete (Remove-Item)": "PowerShell 批量删除文件,内容丢失",
    "PowerShell encoded command execution": "运行加密编码的 PowerShell 命令(无法直接看清内容,警惕)",
    "Windows PowerShell destructive delete": "PowerShell 批量删除文件,内容丢失",
    "Windows cmd destructive delete": "Windows 命令行批量删除文件,内容丢失",
    "Windows destructive delete (recursive/quiet switch)": "Windows 静默递归删除,不问确认直接删",
    "access to Hermes secrets (Windows path)": "读取 Hermes 保存的密钥文件",
    "access to SSH keys (Windows path)": "读取 SSH 私钥(敏感凭据)",
    "delete backups (wbadmin)": "删除 Windows 系统备份",
    "delete volume shadow copies (vssadmin)": "删除卷影副本,被删文件将无法恢复",
    "disk partitioning (diskpart)": "重新划分磁盘分区,操作失误整盘数据不保",
    "docker compose restart/stop/kill/down (container lifecycle)": "停止/重启 Docker 容器组,跑着的服务会断",
    "docker context use (switches default daemon for future commands)": "切换 Docker 默认指向的服务器,后续命令作用到别处",
    "docker restart/stop/kill (container lifecycle)": "停止/重启 Docker 容器",
    "docker with daemon redirect (--context: alternate daemon)": "让 Docker 连到指定的另一台服务器",
    "docker with remote daemon redirect (-H/--host)": "让 Docker 连到指定的另一台服务器",
    "docker/podman daemon redirect via environment (DOCKER_HOST/CONTAINER_HOST)": "通过环境变量把容器操作指向别的服务器",
    "execute remote content via Invoke-Expression": "把网上下载的内容直接在电脑上运行,极危险",
    "execute remote content via command substitution": "把命令替换取回的内容直接运行,极危险",
    "find -exec/-execdir rm": "按搜索结果批量删除文件",
    "force kill processes (Stop-Process -Force)": "PowerShell 强制杀进程",
    "force kill processes (killall -KILL)": "按名字强制杀进程",
    "force kill processes (killall -s KILL)": "按名字强制杀进程",
    "force kill processes (taskkill /F)": "Windows 强制杀进程",
    "force stop service (Stop-Service -Force)": "强制停止某个系统服务",
    "format drive (format.com)": "格式化 Windows 磁盘,盘上数据清空",
    "format filesystem (Format-Volume)": "格式化磁盘卷,盘上数据清空",
    "git branch force delete (long flags)": "强制删除代码分支,未合并的内容会丢",
    "git branch force delete (long flags, force-first)": "强制删除代码分支,未合并的内容会丢",
    "grant Everyone access (icacls)": "把文件权限开放给所有用户(安全隐患)",
    "kill process via backtick pgrep/pidof expansion (self-termination)": "按名字批量杀进程,可能误伤 Hermes 自己",
    "kill process via pgrep/pidof expansion (self-termination)": "按名字批量杀进程,可能误伤 Hermes 自己",
    "kill processes by regex (killall -r)": "按正则匹配批量杀进程,可能误伤",
    "modify boot configuration (bcdedit /set)": "修改 Windows 启动配置,电脑可能开不了机",
    "pipe decoded content to shell (possible command obfuscation)": "把解码后的内容当命令运行(故意隐藏真实内容,警惕)",
    "pipe openssl-decoded content to shell (possible command obfuscation)": "把解密后的内容当命令运行(故意隐藏真实内容,警惕)",
    "pipe remote content to PowerShell (iwr | iex)": "下载远程内容直接在 PowerShell 运行,极危险",
    "pipe tr-transformed output to shell (possible command obfuscation)": "把变形后的内容当命令运行(隐藏内容,警惕)",
    "pipe xxd-decoded content to shell (possible command obfuscation)": "把十六进制解码内容当命令运行(隐藏内容,警惕)",
    "podman remote mode (-r/--remote: remote daemon)": "容器操作发往远程服务器执行",
    "podman with remote daemon redirect (--url/--connection/--identity)": "容器操作发往远程服务器执行",
    "registry delete (reg delete)": "删除 Windows 注册表项,可能破坏系统/软件",
    "registry value delete (Remove-ItemProperty -Force)": "删除 Windows 注册表值,可能破坏系统/软件",
    "reset ACLs recursively (icacls /reset)": "批量重置文件权限,原有访问控制丢失",
    "shell execution via heredoc": "内嵌一段脚本直接运行",
    "stop/delete service (sc)": "停止或删除某个 Windows 服务",
    "stop/restart hermes launchd service (kills running agents)": "重启 Hermes 后台服务,正在跑的任务会中断",
    "sudo with combined-flag privilege escalation": "用管理员权限执行(提权)",
    "sudo with privilege flag (stdin/askpass/shell/list)": "用管理员权限执行(提权)",
    "wipe disk (Clear-Disk)": "抹掉整块磁盘,数据全部清空",
    "wipe free space (cipher /w)": "覆写磁盘空闲空间,已删除文件将无法恢复",
    "unknown": "未识别的风险",
}


def _is_windows() -> bool:
    return sys.platform.startswith("win")


def _cn_reason(description: str) -> str:
    """Translate a '; '-joined English rule description to Chinese."""
    if not description:
        return "危险命令"
    parts = [p.strip() for p in description.split(";") if p.strip()]
    return " + ".join(_DESC_CN.get(p, p) for p in parts)


def _beep_triple():
    """One alarm burst: three rising tones (~0.8s total)."""
    try:
        import winsound
        for freq in (2093, 2093, 2637):
            winsound.Beep(freq, 180)
    except Exception:
        try:
            print("\a" * 3, end="", flush=True)
        except Exception:
            pass

# ------------------------------------------------------------------
# Custom alert sound (v1.1.0). Drop a WAV file named approval.wav next
# to this plugin — or point APPROVAL_NOTIFIER_SOUND at one — and it
# loops (async, non-blocking) while an approval is pending, instead of
# the built-in beep+alarm. mp3s must be converted first, e.g.:
#   ffmpeg -i ring.mp3 -af "apad=pad_dur=29.3" -ac 1 -ar 44100 approval.wav
# (the apad silence sets the repeat interval between chimes — ~30s is a
# polite default; 3s gives an insistent alarm).
# Winsound is Windows-only; on other platforms this degrades to the
# legacy beep loop.
# ------------------------------------------------------------------
_SND_FILENAME, _SND_ASYNC, _SND_LOOP, _SND_PURGE = 0x20000, 0x1, 0x8, 0x0


def _find_sound() -> str:
    cand = (os.getenv("APPROVAL_NOTIFIER_SOUND", "") or
            os.path.join(os.path.dirname(os.path.abspath(__file__)),
                         "approval.wav"))
    return cand if cand.lower().endswith(".wav") and os.path.isfile(cand) else ""


def _play_sound_loop(path: str) -> bool:
    try:
        import winsound
        winsound.PlaySound(path, _SND_FILENAME | _SND_ASYNC | _SND_LOOP)
        return True
    except Exception:
        return False


def _stop_sound():
    try:
        import winsound
        winsound.PlaySound(None, _SND_PURGE)
    except Exception:
        pass


def _send_toast(title: str, body: str, *, alarm: bool = True) -> None:
    """Pop a Windows Toast. Title/body are XML-escaped (v0.2 fix: command
    text can contain < & etc. which previously broke the toast XML).

    XML goes to PowerShell base64-encoded so arbitrary command text can
    never break quoting. Fire-and-forget subprocess: a hung PowerShell can
    not block Hermes.
    """
    body = (body or "").strip()
    if len(body) > 300:
        body = body[:297] + "..."
    audio = ('<audio src="ms-winsoundevent:Notification.Looping.Alarm"/>'
             if alarm else "")
    xml = (
        '<toast scenario="reminder">'
        '<visual><binding template="ToastGeneric">'
        f"<text>{escape(title)}</text>"
        f"<text>{escape(body)}</text>"
        "</binding></visual>"
        f"{audio}"
        "</toast>"
    )
    b64 = base64.b64encode(xml.encode("utf-8")).decode("ascii")
    ps = (
        "$ErrorActionPreference='SilentlyContinue';"
        "[Windows.UI.Notifications.ToastNotificationManager,"
        "Windows.UI.Notifications,ContentType=WindowsRuntime]|Out-Null;"
        "[Windows.Data.Xml.Dom.XmlDocument,"
        "Windows.Data.Xml.Dom.XmlDocument,ContentType=WindowsRuntime]|Out-Null;"
        f"$x=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('{b64}'));"
        "$doc=New-Object Windows.Data.Xml.Dom.XmlDocument;"
        "$doc.LoadXml($x);"
        "$t=New-Object Windows.UI.Notifications.ToastNotification($doc);"
        f"[Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier('{_AUMID}').Show($t)"
    )
    encoded = base64.b64encode(ps.encode("utf-16-le")).decode("ascii")
    subprocess.Popen(
        ["powershell.exe", "-NoProfile", "-NonInteractive",
         "-WindowStyle", "Hidden", "-EncodedCommand", encoded],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        creationflags=(0x08000000 if _is_windows() else 0),  # CREATE_NO_WINDOW
    )


# ------------------------------------------------------------------
# Terminal rendering (v1.2.0): fixed-thought-path Chinese blocks are
# printed INTO the terminal while the y/n prompt is waiting, not only
# pushed as toasts. cli._cprint is the same channel the core approval
# modal itself uses to write during the wait (timeout line), so it is
# safe against the prompt_toolkit UI; plain print is the fallback.
# ------------------------------------------------------------------
_print_lock = threading.Lock()
_BOX_W = 72


def _term_print(lines):
    """Print a list of lines to the terminal, serialized across threads."""
    with _print_lock:
        try:
            try:
                from cli import _cprint
                for ln in lines:
                    _cprint(ln)
            except Exception:
                sys.stdout.write("\n".join(lines) + "\n")
                sys.stdout.flush()
        except Exception as exc:
            logger.debug("approval-notifier: term print failed: %s", exc)


def _box(title, lines):
    """Wrap lines into a light box with a titled top border."""
    import textwrap
    out = [f"╔══ {title} " + "═" * max(2, _BOX_W - 5 - len(title))]
    for ln in lines:
        for seg in textwrap.wrap(str(ln), width=_BOX_W - 6) or [""]:
            out.append(f"║ {seg}")
    out.append("╚" + "═" * _BOX_W)
    return out


# ------------------------------------------------------------------
# Stage 2: LLM-generated Chinese explanation (fixed 5-step path)
# ------------------------------------------------------------------

_EXPLAIN_FIELDS = ("对象", "动作", "后果", "可逆性", "建议")


def _explain_command(command: str, reason_cn: str):
    """Ask the user's active main model for the fixed 5-line breakdown:
    对象 / 动作 / 后果 / 可逆性 / 建议.

    Calls agent.auxiliary_client.call_llm directly with the model section
    read fresh from config (so model switches are picked up). Deliberately
    NOT ctx.llm/PluginLlm: with task=None its "auto" chain misroutes to a
    relay that rejects the key (401 Invalid api_key format, verified
    2026-09-12). Returns list of "(field, text)" lines or None on failure.
    """
    try:
        from hermes_cli.config import load_config
        from agent.auxiliary_client import call_llm
        cfg = load_config() or {}
        # Prefer an explicitly configured auxiliary.approval model (e.g. a
        # fast free endpoint) so explanations survive a congested main
        # relay; fall back to the active main model.
        aux = (cfg.get("auxiliary", {}) or {}).get("approval", {}) or {}
        m = cfg.get("model", {}) or {}
        model = aux.get("model") or m.get("default")
        base_url = aux.get("base_url") or m.get("base_url")
        api_key = aux.get("api_key") or m.get("api_key")
        if not (base_url and api_key and model):
            return None
        prompt = (
            "你是中文安全助手,服务对象是完全不懂命令行的用户。下面这条终端命令被 "
            f"Hermes 审批拦截,规则标记:{reason_cn}。\n\n命令:\n"
            f"{command[:_LLM_MAX_INPUT_CHARS]}\n\n"
            "按以下固定顺序分析并输出,严格5行,每行以字段名紧跟半角冒号开头"
            "(格式:对象:xxx,冒号前后不得有空格),不要任何其他文字、不要代码块、不要序号:\n"
            "对象:命令作用的具体文件/目录/服务/远端,引用真实路径\n"
            "动作:批准后会发生的操作,一句中文\n"
            "后果:最坏情况,一句中文,不超过40字\n"
            "可逆性:可撤销|部分可撤销|不可撤销 三选一,加一句中文说明恢复办法或代价\n"
            "建议:放行|拒绝|请人工确认 三选一,加一句中文理由,不超过30字"
        )
        response = call_llm(
            task=None,
            model=model,
            base_url=base_url,
            api_key=api_key,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2, max_tokens=900, timeout=_LLM_TIMEOUT_S,
        )
        text = ""
        try:
            text = response.choices[0].message.content or ""
        except Exception:
            pass
        # reasoning models wrap output in <think>...</think>
        if "</think>" in text:
            text = text.split("</think>")[-1]
        parsed = {}
        for raw in (l.strip().lstrip("-* 　") for l in text.splitlines() if l.strip()):
            for f in _EXPLAIN_FIELDS:
                if f in parsed:
                    continue
                for head in (f + ":", f + "：", f + " :", f + " ："):
                    if raw.startswith(head):
                        parsed[f] = raw[len(head):].strip()
                        break
        if not parsed:
            return None
        # Missing fields get ONE cheap follow-up pass (models drop lines
        # occasionally); still-missing ones fall back to a static hint.
        missing = [f for f in _EXPLAIN_FIELDS if f not in parsed]
        if missing and len(missing) <= 3:
            try:
                reask = ("把刚才答案里缺失的字段各补一行,格式'字段名:内容'"
                         "(字段名后紧跟冒号无空格)。只补这些:"
                         + "、".join(missing) + "。命令:\n"
                         + command[:500])
                r2 = call_llm(
                    task=None, model=model,
                    base_url=base_url, api_key=api_key,
                    messages=[
                        {"role": "user", "content": prompt},
                        {"role": "assistant", "content": text[:800]},
                        {"role": "user", "content": reask}],
                    temperature=0.0, max_tokens=400, timeout=12)
                t2 = ""
                try:
                    t2 = r2.choices[0].message.content or ""
                except Exception:
                    pass
                if "</think>" in t2:
                    t2 = t2.split("</think>")[-1]
                for raw in (l.strip().lstrip("-* 　") for l in t2.splitlines() if l.strip()):
                    for f in missing:
                        for head in (f + ":", f + "：", f + " :", f + " ："):
                            if raw.startswith(head) and f not in parsed:
                                parsed[f] = raw[len(head):].strip()
            except Exception:
                pass
        return [(f, parsed.get(f, "(模型未给出,按最坏情况对待)"))
                for f in _EXPLAIN_FIELDS]
    except Exception as exc:
        logger.debug("approval-notifier: LLM explain failed: %s", exc)
        return None


def _explain_worker(command: str, reason_cn: str, my_gen: int, started: float):
    """Stage-2 thread: fixed-path explanation → terminal box (primary)
    + toast (secondary). v1.2.2: late results are still delivered (marked
    as 补发) — a slow endpoint should not cost the user the explanation
    they were promised. Superseded-by-newer-request results are dropped."""
    try:
        fields = _explain_command(command, reason_cn)
        with _gen_lock:
            superseded = _gen != my_gen
        if superseded:
            return                 # a newer approval took over the display
        if fields is None:
            if not _stop.is_set():
                _term_print(_box("📖 AI 解读暂不可用（模型超时/不可达），请凭上方底稿决定",
                                 []))
            return
        late = _stop.is_set()
        title = ("📖 AI 解读（审批已结束，以下为补发，供事后核对）"
                 if late else "📖 AI 解读（仅供参考，决定权在你）")
        lines = [f"{f}: {t}" for f, t in fields]
        _term_print(_box(title, lines))
        if not late:
            _send_toast("📖 Hermes 命令解读", "\n".join(lines), alarm=False)
    except Exception as exc:
        logger.debug("approval-notifier: explain worker failed: %s", exc)


def _alert_worker(command: str, reason_cn: str, my_gen: int):
    """Stage-1: immediate toast + alarm, keep alerting until resolved."""
    wav = _find_sound()
    has_sound = _play_sound_loop(wav) if wav else False
    try:
        _send_toast("⏰ Hermes 审批请求", f"⚠ {reason_cn}\n命令: {command}",
                    alarm=not has_sound)
    except Exception as exc:
        logger.debug("approval-notifier toast failed: %s", exc)
    if not has_sound:
        try:
            _beep_triple()
        except Exception:
            pass
    # Stage 2 runs in its own thread so a slow LLM never delays the alarm.
    threading.Thread(target=_explain_worker,
                     args=(command, reason_cn, my_gen, time.time()),
                     daemon=True).start()
    deadline = time.time() + _BELL_MAX_S
    if has_sound:
        # Custom WAV loops on its own; just police the hard deadline.
        while not _stop.wait(_BELL_INTERVAL_S):
            if time.time() >= deadline:
                break
        _stop_sound()
        return
    while not _stop.wait(_BELL_INTERVAL_S):
        if time.time() >= deadline:
            break
        try:
            _beep_triple()
        except Exception:
            break


def on_pre_approval_request(**kwargs):
    """pre_approval_request hook: instant Chinese base-block in the
    terminal + toast + alarm; fixed-path AI explanation follows async."""
    command = kwargs.get("command", "") or ""
    description = kwargs.get("description", "") or ""
    surface = kwargs.get("surface", "")
    reason_cn = _cn_reason(description)
    logger.info("approval-notifier: approval requested (surface=%s, %s)",
                surface, reason_cn)
    _stop.clear()
    # Stage 1 in-terminal: deterministic, zero latency — always visible
    # even if the model/endpoint is down.
    _term_print(_box("⚠ 审批请求", [
        f"风险类型: {reason_cn}",
        f"命令: {command[:300]}" + ("…" if len(command) > 300 else ""),
        "AI 正在解读命令，几秒后显示在下方…",
    ]))
    with _gen_lock:
        global _gen
        _gen += 1
        my_gen = _gen
    threading.Thread(target=_alert_worker,
                     args=(command, reason_cn, my_gen), daemon=True).start()


def on_post_approval_response(**kwargs):
    """post_approval_response hook: stop alarm sound/beeps, suppress
    pending stage-2 toasts."""
    _stop.set()
    _stop_sound()


def register(ctx):
    global _ctx
    _ctx = ctx
    ctx.register_hook("pre_approval_request", on_pre_approval_request)
    ctx.register_hook("post_approval_response", on_post_approval_response)
