"""approval-notifier — never miss or misread an approval prompt again.

v1.0.0: two-stage alerts with plain-language Chinese command explanations.

Scenario: the user backgrounds the terminal running Hermes. When a
dangerous-command approval prompt appears, they (a) may not see it
(60s default auto-deny) and (b) can't read raw shell syntax anyway.

Behavior now, in two stages:
- Stage 1 (immediate): Windows Toast with the risk category translated
  to Chinese via a static table (deterministic, zero latency, no LLM),
  plus the raw command. Alarm tone + console beeps start immediately
  and repeat every 15s until the approval is resolved.
- Stage 2 (a few seconds later, async): a second Toast titled
  「命令解读」 generated by the user's ACTIVE main model (via
  agent.auxiliary_client.call_llm with config.yaml's model section,
  read fresh per call so model switches are honored): one line saying
  what the command concretely does, one line with a risk verdict. If
  the LLM fails/times out, stage 2 is silently skipped — stage 1
  already fired.

The approval decision itself still happens in the terminal (y/n); the
toasts are observers only. Never blocks the agent thread.
"""

import base64
import logging
import subprocess
import sys
import threading
import time
from xml.sax.saxutils import escape

logger = logging.getLogger(__name__)

_BELL_INTERVAL_S = 15.0        # repeating beep interval
_BELL_MAX_S = 900.0            # hard stop: 15 minutes of beeping max
_LLM_TIMEOUT_S = 25.0          # stage-2 explanation budget
_LLM_MAX_INPUT_CHARS = 2000    # truncate huge commands before the LLM
_AUMID = ("{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}"
          r"\WindowsPowerShell\v1.0\powershell.exe")

_stop = threading.Event()
_gen = 0                       # request generation counter
_gen_lock = threading.Lock()
_ctx = None                    # plugin ctx (saved at register()) for ctx.llm

# ------------------------------------------------------------------
# Static EN->CN translation for Hermes' known approval rule names
# (from tools/approval.py DANGEROUS_PATTERNS / HARDLINE_PATTERNS).
# Unknown strings pass through untranslated.
# ------------------------------------------------------------------
_DESC_CN = {
    "recursive delete of root filesystem": "对根文件系统递归删除(极危)",
    "recursive delete of system directory": "对系统目录递归删除",
    "recursive delete of home directory": "对家目录递归删除",
    "format filesystem (mkfs)": "格式化磁盘分区(mkfs)",
    "dd to raw block device": "dd 直写物理磁盘设备",
    "redirect to raw block device": "输出重定向写入物理磁盘",
    "fork bomb": "fork 炸弹(耗尽系统进程)",
    "kill all processes": "杀死所有进程",
    "force kill processes": "强制杀进程",
    "system shutdown/reboot": "关机/重启系统",
    "init 0/6 (shutdown/reboot)": "切换到停机/重启运行级",
    "systemctl poweroff/reboot": "经服务管理器关机/重启",
    "telinit 0/6 (shutdown/reboot)": "telinit 停机/重启",
    "stop/restart system service": "停止/重启系统服务",
    "sudo password guessing via stdin (sudo -S)": "经管道尝试 sudo 密码",
    "delete in root path": "在根路径下删除文件",
    "recursive delete": "递归删除目录",
    "recursive delete (long flag)": "递归删除目录",
    "world/other-writable permissions": "放开所有人可写权限(777 类)",
    "recursive world/other-writable (long flag)": "递归放开所有人可写权限",
    "recursive chown to root": "递归把文件归属改为 root",
    "recursive chown to root (long flag)": "递归把文件归属改为 root",
    "format filesystem": "格式化文件系统",
    "disk copy": "磁盘级复制(dd),可整盘覆盖数据",
    "write to block device": "写入块设备",
    "SQL DROP": "SQL 删表/删库",
    "SQL DELETE without WHERE": "SQL 无条件全表删除",
    "SQL TRUNCATE": "SQL 清空整表",
    "overwrite system config": "覆盖系统配置文件",
    "overwrite system file via tee": "用 tee 覆盖系统文件",
    "overwrite system file via redirection": "用重定向覆盖系统文件",
    "overwrite project env/config via tee": "用 tee 覆盖项目配置/环境变量文件",
    "overwrite project env/config via redirection": "用重定向覆盖项目配置/环境变量文件",
    "overwrite project env/config file": "覆盖项目配置/环境变量文件",
    "copy/move file into /etc/": "复制/移动文件进 /etc/",
    "in-place edit of system config": "原地编辑系统配置",
    "in-place edit of system config (long flag)": "原地编辑系统配置",
    "shell command via -c/-lc flag": "以 -c 方式执行 shell 片段",
    "script execution via -e/-c flag": "以 -e/-c 内联执行脚本(常见误报)",
    "script execution via heredoc": "以 heredoc 内嵌脚本执行",
    "pipe remote content to shell": "下载远程内容并直接执行(curl|sh)",
    "execute remote script via process substitution": "以进程替换执行远程脚本",
    "chmod +x followed by immediate execution": "先加执行权限再立即运行(下载脚本套路)",
    "xargs with rm": "xargs 批量删除文件",
    "find -exec rm": "find 批量删除文件",
    "find -delete": "find 批量删除文件",
    "stop/restart hermes gateway (kills running agents)": "停止/重启 Hermes 网关(中断运行中的任务)",
    "hermes update (restarts gateway, kills running agents)": "更新 Hermes(重启网关,中断任务)",
    "start gateway outside systemd (use 'systemctl --user restart hermes-gateway')": "非 systemd 方式启动网关",
    "kill hermes/gateway process (self-termination)": "杀死 Hermes 自身进程",
    "kill process via pgrep expansion (self-termination)": "经 pgrep 匹配杀进程(可能伤及自身)",
    "kill process via backtick pgrep expansion (self-termination)": "经 pgrep 匹配杀进程(可能伤及自身)",
    "git reset --hard (destroys uncommitted changes)": "git 硬回退(丢失未提交修改)",
    "git force push (rewrites remote history)": "git 强推(改写远端历史)",
    "git force push short flag (rewrites remote history)": "git 强推(改写远端历史)",
    "git clean with force (deletes untracked files)": "git 强制清理未跟踪文件",
    "git branch force delete": "git 强制删除分支",
    "unknown": "未知风险",
}


def _is_windows() -> bool:
    return sys.platform.startswith("win")


def _cn_reason(description: str) -> str:
    """Translate a '; '-joined English rule description to Chinese."""
    if not description:
        return "危险命令"
    parts = [p.strip() for p in description.split(";") if p.strip()]
    return " + ".join(_DESC_CN.get(p, p) for p in parts)


def _beep_triple():
    """One alarm burst: three rising tones (~0.8s total)."""
    try:
        import winsound
        for freq in (2093, 2093, 2637):
            winsound.Beep(freq, 180)
    except Exception:
        try:
            print("\a" * 3, end="", flush=True)
        except Exception:
            pass


def _send_toast(title: str, body: str, *, alarm: bool = True) -> None:
    """Pop a Windows Toast. Title/body are XML-escaped (v0.2 fix: command
    text can contain < & etc. which previously broke the toast XML).

    XML goes to PowerShell base64-encoded so arbitrary command text can
    never break quoting. Fire-and-forget subprocess: a hung PowerShell can
    not block Hermes.
    """
    body = (body or "").strip()
    if len(body) > 300:
        body = body[:297] + "..."
    audio = ('<audio src="ms-winsoundevent:Notification.Looping.Alarm"/>'
             if alarm else "")
    xml = (
        '<toast scenario="reminder">'
        '<visual><binding template="ToastGeneric">'
        f"<text>{escape(title)}</text>"
        f"<text>{escape(body)}</text>"
        "</binding></visual>"
        f"{audio}"
        "</toast>"
    )
    b64 = base64.b64encode(xml.encode("utf-8")).decode("ascii")
    ps = (
        "$ErrorActionPreference='SilentlyContinue';"
        "[Windows.UI.Notifications.ToastNotificationManager,"
        "Windows.UI.Notifications,ContentType=WindowsRuntime]|Out-Null;"
        "[Windows.Data.Xml.Dom.XmlDocument,"
        "Windows.Data.Xml.Dom.XmlDocument,ContentType=WindowsRuntime]|Out-Null;"
        f"$x=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('{b64}'));"
        "$doc=New-Object Windows.Data.Xml.Dom.XmlDocument;"
        "$doc.LoadXml($x);"
        "$t=New-Object Windows.UI.Notifications.ToastNotification($doc);"
        f"[Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier('{_AUMID}').Show($t)"
    )
    encoded = base64.b64encode(ps.encode("utf-16-le")).decode("ascii")
    subprocess.Popen(
        ["powershell.exe", "-NoProfile", "-NonInteractive",
         "-WindowStyle", "Hidden", "-EncodedCommand", encoded],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        creationflags=(0x08000000 if _is_windows() else 0),  # CREATE_NO_WINDOW
    )


# ------------------------------------------------------------------
# Stage 2: LLM-generated Chinese explanation
# ------------------------------------------------------------------

def _explain_command(command: str, reason_cn: str):
    """Ask the user's active main model for a 2-line Chinese explanation.

    Calls agent.auxiliary_client.call_llm directly with the model section
    read fresh from config (so model switches are picked up). Deliberately
    NOT ctx.llm/PluginLlm: with task=None its "auto" chain misroutes to a
    relay that rejects the key (401 Invalid api_key format, verified
    2026-09-12). Returns (action_line, risk_line) or None on any failure.
    """
    try:
        from hermes_cli.config import load_config
        from agent.auxiliary_client import call_llm
        m = (load_config() or {}).get("model", {}) or {}
        if not (m.get("base_url") and m.get("api_key") and m.get("default")):
            return None
        prompt = (
            "你是中文安全助手,服务对象是不懂命令行的用户。下面这条终端命令被 Hermes "
            f"审批拦截,标记原因:{reason_cn}。\n\n命令:\n{command[:_LLM_MAX_INPUT_CHARS]}\n\n"
            "请严格按以下格式回复两行,不要任何其他文字、不要代码块:\n"
            "做什么: <一句中文,不超过45字,说明具体操作对象和路径>\n"
            "风险: <高危|中危|低危>。<一句中文,不超过45字,说明批准后可能的后果>"
        )
        response = call_llm(
            task=None,
            model=m.get("default"),
            base_url=m.get("base_url"),
            api_key=m.get("api_key"),
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2, max_tokens=700, timeout=_LLM_TIMEOUT_S,
        )
        text = ""
        try:
            text = response.choices[0].message.content or ""
        except Exception:
            pass
        # reasoning models wrap output in <think>...</think>
        if "</think>" in text:
            text = text.split("</think>")[-1]
        lines = [l.strip() for l in text.splitlines() if l.strip()]
        action = next((l for l in lines if l.startswith("做什么")), "")
        risk = next((l for l in lines if l.startswith("风险")), "")
        if not action and len(lines) >= 2:
            action, risk = lines[0], lines[1]
        if not action and not risk:
            return None
        return (action or "做什么: (模型未说明)", risk or "风险: (模型未评级)")
    except Exception as exc:
        logger.debug("approval-notifier: LLM explain failed: %s", exc)
        return None


def _explain_worker(command: str, reason_cn: str, my_gen: int):
    """Stage-2 thread: generate explanation, toast it IF the approval is
    still pending and this is still the latest request."""
    try:
        pair = _explain_command(command, reason_cn)
        if pair is None:
            return
        if _stop.is_set():
            return                     # already resolved — don't spam
        with _gen_lock:
            if _gen != my_gen:
                return                 # a newer approval superseded this one
        _send_toast("📖 Hermes 命令解读",
                    f"{pair[0]}\n{pair[1]}", alarm=False)
    except Exception as exc:
        logger.debug("approval-notifier: explain worker failed: %s", exc)


def _alert_worker(command: str, reason_cn: str, my_gen: int):
    """Stage-1: immediate toast + beeps, then repeating beeps until resolved."""
    try:
        _send_toast("⏰ Hermes 审批请求", f"⚠ {reason_cn}\n命令: {command}")
    except Exception as exc:
        logger.debug("approval-notifier toast failed: %s", exc)
    try:
        _beep_triple()
    except Exception:
        pass
    # Stage 2 runs in its own thread so a slow LLM never delays the alarm.
    threading.Thread(target=_explain_worker, args=(command, reason_cn, my_gen),
                     daemon=True).start()
    deadline = time.time() + _BELL_MAX_S
    while not _stop.wait(_BELL_INTERVAL_S):
        if time.time() >= deadline:
            break
        try:
            _beep_triple()
        except Exception:
            break


def on_pre_approval_request(**kwargs):
    """pre_approval_request hook: alarm now, Chinese explanation async."""
    command = kwargs.get("command", "") or ""
    description = kwargs.get("description", "") or ""
    surface = kwargs.get("surface", "")
    reason_cn = _cn_reason(description)
    logger.info("approval-notifier: approval requested (surface=%s, %s)",
                surface, reason_cn)
    _stop.clear()
    with _gen_lock:
        global _gen
        _gen += 1
        my_gen = _gen
    threading.Thread(target=_alert_worker,
                     args=(command, reason_cn, my_gen), daemon=True).start()


def on_post_approval_response(**kwargs):
    """post_approval_response hook: stop the alarm, suppress pending stage-2."""
    _stop.set()


def register(ctx):
    global _ctx
    _ctx = ctx
    ctx.register_hook("pre_approval_request", on_pre_approval_request)
    ctx.register_hook("post_approval_response", on_post_approval_response)
